name: pythonn
on:
  issues:
    types: [opened]

jobs:
  play:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: imageine if this worked lmfao        
        run: pip install -r requirements.txt
      
      - name: workmk     
        run: python main.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          WORKSPACE_ID: ${{ secrets.WORKSPACE_ID }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY_OWNER: ${{ github.repository_owner }}
        
      - name: Commit and push
        run: |
          git diff
          git add .
          git config --global user.email "github-action-bot@example.com"
          git config --global user.name "GitHub Action Bot"
          git commit -m "Updated game" -a
          git push
