name: python
on:
  issues:
    types: [opened]

jobs:
  play:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Update game
        run: python connect_four.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          WORKSPACE_ID: ${{ secrets.WORKSPACE_ID }}
        
      - name: Commit and push
        run: |
          git diff
          git add .
          git config --global user.email "github-action-bot@example.com"
          git config --global user.name "GitHub Action Bot"
          git commit -m "Updated game" -a
          git push
